url1: https://test-stand.gb.ru/gateway/login
#username: kitty89
#password: 61d96a3985
url2: https://test-stand.gb.ru/api/posts
description: test description
username: Petrr
password: fa258a35d9
title: 'New_title'
